# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-12 11:05


from django.db import migrations, models
import django.db.models.deletion
import imageserver.models
import imageserver.storage


class Migration(migrations.Migration):

    dependencies = [
        ('imageserver', '0003_auto_20150915_1100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='layer',
            name='mask',
            field=models.FileField(blank=True, null=True, storage=imageserver.storage.LayerStorage(), upload_to=imageserver.models.get_mask_upload_path),
        ),
        migrations.AlterField(
            model_name='namedmask',
            name='mask',
            field=models.FileField(storage=imageserver.storage.NamedMaskStorage(), upload_to=imageserver.models.get_named_mask_upload_path),
        ),
        migrations.AlterField(
            model_name='servicelayer',
            name='layer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='imageserver.Layer'),
        ),
    ]
