# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-01 09:07
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('imageserver', '0004_auto_20170612_1105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='supported_srs',
            field=models.CharField(help_text=b'Comma separated list of supported EPSG codes', max_length=400, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:\\,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')]),
        ),
    ]
