# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-23 13:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('giscube', '0005_auto_20180529_1051'),
        ('imageserver', '0007_service_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='imageserver_services', to='giscube.Category'),
        ),
    ]
