# Generated by Django 2.1.7 on 2019-03-05 10:11

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('imageserver', '0008_auto_20180423_1322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='layer',
            name='image',
            field=models.CharField(help_text='Image file or folder with tiled images', max_length=255),
        ),
        migrations.AlterField(
            model_name='layer',
            name='projection',
            field=models.IntegerField(help_text='EPSG code'),
        ),
        migrations.AlterField(
            model_name='namedmask',
            name='projection',
            field=models.IntegerField(help_text='EPSG code'),
        ),
        migrations.AlterField(
            model_name='service',
            name='projection',
            field=models.IntegerField(help_text='EPSG code'),
        ),
        migrations.AlterField(
            model_name='service',
            name='supported_srs',
            field=models.CharField(help_text='Comma separated list of supported EPSG codes', max_length=400, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:\\,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')]),
        ),
        migrations.AlterField(
            model_name='service',
            name='visibility',
            field=models.CharField(choices=[('private', 'Private'), ('public', 'Public')], default='private', max_length=10),
        ),
    ]
