# Generated by Django 2.2.9 on 2020-01-15 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imageserver', '0012_auto_20190507_0914'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='legend',
            field=models.TextField(blank=True, null=True, verbose_name='legend'),
        ),
    ]
