# Generated by Django 2.2.17 on 2020-11-23 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imageserver', '0018_serviceresource_content_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='wms_single_image',
            field=models.BooleanField(default=False, verbose_name='prefer single image'),
        )
    ]
