# Generated by Django 2.2.17 on 2020-11-23 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imageserver', '0019_single_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceresource',
            name='content_type',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='format'),
        ),
    ]
