# Generated by Django 2.2.11 on 2020-05-06 05:08

from django.db import migrations


def migrate_to_anonymous_view(apps, schema_editor):
    Service = apps.get_model('imageserver', 'Service')
    for layer in Service.objects.all():
        layer.anonymous_view = layer.visibility == 'public'
        layer.authenticated_user_view = layer.visibility == 'private'
        layer.save()


def undo_migrate_to_anonymous_view(apps, schema_editor):
    Service = apps.get_model('imageserver', 'Service')
    for layer in Service.objects.all():
        if layer.anonymous_view:
            layer.visibility == 'public'
        else:
            layer.visibility == 'private'
        layer.save()


class Migration(migrations.Migration):

    dependencies = [
        ('imageserver', '0022_auto_20210321_0817'),
    ]
    operations = [
        migrations.RunPython(migrate_to_anonymous_view, undo_migrate_to_anonymous_view),
        migrations.RemoveField(
            model_name='service',
            name='visibility',
        ),
    ]
