# Generated by Django 3.2.17 on 2023-10-06 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imageserver', '0025_auto_20230314_1233'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='choose_individual_layers',
            field=models.BooleanField(default=False, verbose_name='choose individual layers'),
        ),
        migrations.AddField(
            model_name='service',
            name='layers',
            field=models.TextField(blank=True, null=True, verbose_name='layers'),
        ),
        migrations.AddField(
            model_name='service',
            name='read_layers_automatically',
            field=models.BooleanField(default=False, verbose_name='read layers automatically'),
        ),
    ]
