# Generated by Django 3.2.17 on 2024-10-10 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imageserver', '0026_auto_20231006_1219'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='tilecache_expiration_time',
            field=models.IntegerField(default=604800, help_text='Time in seconds', verbose_name='cache expiration time'),
        ),
    ]
