# Generated by Django 3.2.17 on 2025-07-03 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imageserver', '0028_auto_20241010_1202'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='catalog_color',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='catalog color'),
        ),
    ]
