# Generated by Django 2.2.27 on 2022-11-16 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VisorUserTrack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, verbose_name='username')),
                ('ip', models.CharField(max_length=20, verbose_name='ip')),
                ('datetime', models.DateTimeField(verbose_name='datetime')),
            ],
            options={
                'verbose_name': 'Visor user track',
                'verbose_name_plural': 'Visor user tracks',
            },
        ),
    ]
