# Generated by Django 3.2.17 on 2023-03-14 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_tracking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visorusertrack',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
