# Generated by Django 3.2.17 on 2024-12-23 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_tracking', '0002_alter_visorusertrack_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='LayerRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('layer_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='layer name')),
                ('datetime', models.DateTimeField(blank=True, null=True, verbose_name='updated date')),
                ('username', models.CharField(max_length=150, verbose_name='username')),
            ],
            options={
                'verbose_name': 'Layer register',
                'verbose_name_plural': 'Layers register',
            },
        ),
        migrations.CreateModel(
            name='ToolRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tool_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='tool name')),
                ('datetime', models.DateTimeField(blank=True, null=True, verbose_name='updated date')),
                ('username', models.CharField(max_length=150, verbose_name='username')),
            ],
            options={
                'verbose_name': 'Tool register',
                'verbose_name_plural': 'Tools register',
            },
        ),
    ]
