# Generated by Django 3.2.17 on 2025-01-15 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_tracking', '0003_layerregister_toolregister'),
    ]

    operations = [
        migrations.AddField(
            model_name='layerregister',
            name='giscube_id',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Giscube ID'),
        ),
        migrations.AlterField(
            model_name='layerregister',
            name='datetime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='datetime'),
        ),
        migrations.AlterField(
            model_name='toolregister',
            name='datetime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='datetime'),
        ),
    ]
