# Generated by Django 3.2.17 on 2025-01-15 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_tracking', '0004_auto_20250115_1157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='layerregister',
            name='username',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='username'),
        ),
        migrations.AlterField(
            model_name='toolregister',
            name='username',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='username'),
        ),
    ]
