# Generated by Django 3.2.17 on 2026-09-10 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_tracking', '0005_auto_20250115_1230'),
    ]

    operations = [
        migrations.AddField(
            model_name='layerregister',
            name='permission',
            field=models.CharField(blank=True, choices=[('public', 'Public'), ('private', 'Private')], help_text='Visibility of the layer when it was registered', max_length=20, null=True, verbose_name='permission'),
        ),
    ]
