# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-26 09:14


import colorfield.fields
from django.db import migrations, models
import django.db.models.deletion
import giscube.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('giscube', '0002_update'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeoJsonLayer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('keywords', models.CharField(blank=True, max_length=200, null=True)),
                ('active', models.BooleanField(default=True)),
                ('visibility', models.CharField(choices=[('private', 'Private'), ('public', 'Public')], default='private', max_length=10)),
                ('visible_on_geoportal', models.BooleanField(default=False)),
                ('shapetype', models.CharField(blank=True, choices=[('marker', 'Marker'), ('line', 'Line'), ('polygon', 'Polygon'), ('Circle', 'Circle')], max_length=20, null=True)),
                ('shape_radius', models.IntegerField(blank=True, null=True)),
                ('stroke_color', colorfield.fields.ColorField(blank=True, default=b'#FF3333', max_length=18, null=True)),
                ('stroke_width', models.IntegerField(blank=True, default=1, null=True)),
                ('stroke_dash_array', models.CharField(blank=True, default='', max_length=25, null=True)),
                ('fill_color', colorfield.fields.ColorField(blank=True, default=b'#FFC300', max_length=18, null=True)),
                ('fill_opacity', models.DecimalField(blank=True, decimal_places=1, default=1, max_digits=2, null=True)),
                ('url', models.CharField(blank=True, max_length=100, null=True)),
                ('data_file', models.FileField(blank=True, null=True, upload_to=giscube.utils.unique_service_directory)),
                ('service_path', models.CharField(max_length=255)),
                ('cache_time', models.IntegerField(blank=True, null=True)),
                ('last_fetch_on', models.DateField(blank=True, null=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='giscube.Category')),
            ],
            options={
                'verbose_name': 'GeoJSONLayer',
                'verbose_name_plural': 'GeoJSONLayers',
            },
        ),
    ]
