# Generated by Django 2.1.9 on 2019-07-01 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layerserver', '0001_squashed_0041_auto_20190612_1532'),
    ]

    operations = [
        migrations.AddField(
            model_name='databaselayer',
            name='tooltip',
            field=models.TextField(blank=True, null=True, verbose_name='tooltip'),
        ),
        migrations.AddField(
            model_name='geojsonlayer',
            name='tooltip',
            field=models.TextField(blank=True, null=True, verbose_name='tooltip'),
        ),
    ]
