# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-26 09:30


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layerserver', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='geojsonlayer',
            name='generated_on',
            field=models.DateField(blank=True, null=True),
        ),
    ]
