# Generated by Django 2.1.9 on 2019-07-02 12:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('layerserver', '0002_auto_20190701_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='databaselayer',
            name='active',
            field=models.BooleanField(default=True, help_text='Enable/disable usage', verbose_name='active'),
        ),
        migrations.AlterField(
            model_name='databaselayer',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='giscube.Category', verbose_name='category'),
        ),
        migrations.AlterField(
            model_name='databaselayer',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='databaselayer',
            name='fill_color',
            field=models.CharField(blank=True, default='#FFC300', max_length=50, null=True, verbose_name='fill color'),
        ),
        migrations.AlterField(
            model_name='databaselayer',
            name='fill_opacity',
            field=models.CharField(blank=True, default='1', max_length=50, null=True, verbose_name='fill opacity'),
        ),
        migrations.AlterField(
            model_name='databaselayer',
            name='icon',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='icon'),
        ),
        migrations.AlterField(
            model_name='databaselayer',
            name='icon_color',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='icon color'),
        ),
        migrations.AlterField(
            model_name='databaselayer',
            name='icon_type',
            field=models.CharField(blank=True, choices=[('fa', 'fa'), ('img', 'img')], max_length=100, null=True, verbose_name='icon type'),
        ),
        migrations.AlterField(
            model_name='databaselayer',
            name='keywords',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='keywords'),
        ),
        migrations.AlterField(
            model_name='databaselayer',
            name='marker_color',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='marker color'),
        ),
        migrations.AlterField(
            model_name='databaselayer',
            name='popup',
            field=models.TextField(blank=True, help_text='Field between curly braces. e.g. {street}', null=True, verbose_name='popup'),
        ),
        migrations.AlterField(
            model_name='databaselayer',
            name='shape_radius',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='shape radius'),
        ),
        migrations.AlterField(
            model_name='databaselayer',
            name='stroke_color',
            field=models.CharField(blank=True, default='#FF3333', max_length=50, null=True, verbose_name='stroke color'),
        ),
        migrations.AlterField(
            model_name='databaselayer',
            name='stroke_dash_array',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='stroke dash array'),
        ),
        migrations.AlterField(
            model_name='databaselayer',
            name='stroke_width',
            field=models.CharField(blank=True, default='1', max_length=50, null=True, verbose_name='stroke width'),
        ),
        migrations.AlterField(
            model_name='databaselayer',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='databaselayer',
            name='tooltip',
            field=models.TextField(blank=True, help_text='Field between curly braces. e.g. {street}', null=True, verbose_name='tooltip'),
        ),
        migrations.AlterField(
            model_name='databaselayer',
            name='visible_on_geoportal',
            field=models.BooleanField(default=False, verbose_name='visible on geoportal'),
        ),
        migrations.AlterField(
            model_name='databaselayerstylerule',
            name='fill_color',
            field=models.CharField(blank=True, default='#FFC300', max_length=50, null=True, verbose_name='fill color'),
        ),
        migrations.AlterField(
            model_name='databaselayerstylerule',
            name='fill_opacity',
            field=models.CharField(blank=True, default='1', max_length=50, null=True, verbose_name='fill opacity'),
        ),
        migrations.AlterField(
            model_name='databaselayerstylerule',
            name='icon',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='icon'),
        ),
        migrations.AlterField(
            model_name='databaselayerstylerule',
            name='icon_color',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='icon color'),
        ),
        migrations.AlterField(
            model_name='databaselayerstylerule',
            name='icon_type',
            field=models.CharField(blank=True, choices=[('fa', 'fa'), ('img', 'img')], max_length=100, null=True, verbose_name='icon type'),
        ),
        migrations.AlterField(
            model_name='databaselayerstylerule',
            name='marker_color',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='marker color'),
        ),
        migrations.AlterField(
            model_name='databaselayerstylerule',
            name='shape_radius',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='shape radius'),
        ),
        migrations.AlterField(
            model_name='databaselayerstylerule',
            name='stroke_color',
            field=models.CharField(blank=True, default='#FF3333', max_length=50, null=True, verbose_name='stroke color'),
        ),
        migrations.AlterField(
            model_name='databaselayerstylerule',
            name='stroke_dash_array',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='stroke dash array'),
        ),
        migrations.AlterField(
            model_name='databaselayerstylerule',
            name='stroke_width',
            field=models.CharField(blank=True, default='1', max_length=50, null=True, verbose_name='stroke width'),
        ),
        migrations.AlterField(
            model_name='geojsonlayer',
            name='active',
            field=models.BooleanField(default=True, help_text='Enable/disable usage', verbose_name='active'),
        ),
        migrations.AlterField(
            model_name='geojsonlayer',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='giscube.Category', verbose_name='category'),
        ),
        migrations.AlterField(
            model_name='geojsonlayer',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='geojsonlayer',
            name='fill_color',
            field=models.CharField(blank=True, default='#FFC300', max_length=50, null=True, verbose_name='fill color'),
        ),
        migrations.AlterField(
            model_name='geojsonlayer',
            name='fill_opacity',
            field=models.CharField(blank=True, default='1', max_length=50, null=True, verbose_name='fill opacity'),
        ),
        migrations.AlterField(
            model_name='geojsonlayer',
            name='icon',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='icon'),
        ),
        migrations.AlterField(
            model_name='geojsonlayer',
            name='icon_color',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='icon color'),
        ),
        migrations.AlterField(
            model_name='geojsonlayer',
            name='icon_type',
            field=models.CharField(blank=True, choices=[('fa', 'fa'), ('img', 'img')], max_length=100, null=True, verbose_name='icon type'),
        ),
        migrations.AlterField(
            model_name='geojsonlayer',
            name='keywords',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='keywords'),
        ),
        migrations.AlterField(
            model_name='geojsonlayer',
            name='marker_color',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='marker color'),
        ),
        migrations.AlterField(
            model_name='geojsonlayer',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='geojsonlayer',
            name='popup',
            field=models.TextField(blank=True, help_text='Field between curly braces. e.g. {street}', null=True, verbose_name='popup'),
        ),
        migrations.AlterField(
            model_name='geojsonlayer',
            name='shape_radius',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='shape radius'),
        ),
        migrations.AlterField(
            model_name='geojsonlayer',
            name='stroke_color',
            field=models.CharField(blank=True, default='#FF3333', max_length=50, null=True, verbose_name='stroke color'),
        ),
        migrations.AlterField(
            model_name='geojsonlayer',
            name='stroke_dash_array',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='stroke dash array'),
        ),
        migrations.AlterField(
            model_name='geojsonlayer',
            name='stroke_width',
            field=models.CharField(blank=True, default='1', max_length=50, null=True, verbose_name='stroke width'),
        ),
        migrations.AlterField(
            model_name='geojsonlayer',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='geojsonlayer',
            name='tooltip',
            field=models.TextField(blank=True, help_text='Field between curly braces. e.g. {street}', null=True, verbose_name='tooltip'),
        ),
        migrations.AlterField(
            model_name='geojsonlayer',
            name='visible_on_geoportal',
            field=models.BooleanField(default=False, verbose_name='visible on geoportal'),
        ),
        migrations.AlterField(
            model_name='geojsonlayerstylerule',
            name='fill_color',
            field=models.CharField(blank=True, default='#FFC300', max_length=50, null=True, verbose_name='fill color'),
        ),
        migrations.AlterField(
            model_name='geojsonlayerstylerule',
            name='fill_opacity',
            field=models.CharField(blank=True, default='1', max_length=50, null=True, verbose_name='fill opacity'),
        ),
        migrations.AlterField(
            model_name='geojsonlayerstylerule',
            name='icon',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='icon'),
        ),
        migrations.AlterField(
            model_name='geojsonlayerstylerule',
            name='icon_color',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='icon color'),
        ),
        migrations.AlterField(
            model_name='geojsonlayerstylerule',
            name='icon_type',
            field=models.CharField(blank=True, choices=[('fa', 'fa'), ('img', 'img')], max_length=100, null=True, verbose_name='icon type'),
        ),
        migrations.AlterField(
            model_name='geojsonlayerstylerule',
            name='marker_color',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='marker color'),
        ),
        migrations.AlterField(
            model_name='geojsonlayerstylerule',
            name='shape_radius',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='shape radius'),
        ),
        migrations.AlterField(
            model_name='geojsonlayerstylerule',
            name='stroke_color',
            field=models.CharField(blank=True, default='#FF3333', max_length=50, null=True, verbose_name='stroke color'),
        ),
        migrations.AlterField(
            model_name='geojsonlayerstylerule',
            name='stroke_dash_array',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='stroke dash array'),
        ),
        migrations.AlterField(
            model_name='geojsonlayerstylerule',
            name='stroke_width',
            field=models.CharField(blank=True, default='1', max_length=50, null=True, verbose_name='stroke width'),
        ),
    ]
