# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-23 06:45


import colorfield.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('giscube', '0004_dbconnection_alias'),
        ('layerserver', '0003_auto_20180521_1232'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataBaseLayer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('keywords', models.CharField(blank=True, max_length=200, null=True)),
                ('active', models.BooleanField(default=True)),
                ('visibility', models.CharField(choices=[('private', 'Private'), ('public', 'Public')], default='private', max_length=10)),
                ('visible_on_geoportal', models.BooleanField(default=False)),
                ('shapetype', models.CharField(blank=True, choices=[('marker', 'Marker'), ('line', 'Line'), ('polygon', 'Polygon'), ('Circle', 'Circle')], max_length=20, null=True)),
                ('shape_radius', models.IntegerField(blank=True, null=True)),
                ('stroke_color', colorfield.fields.ColorField(blank=True, default=b'#FF3333', max_length=18, null=True)),
                ('stroke_width', models.IntegerField(blank=True, default=1, null=True)),
                ('stroke_dash_array', models.CharField(blank=True, default='', max_length=25, null=True)),
                ('fill_color', colorfield.fields.ColorField(blank=True, default=b'#FFC300', max_length=18, null=True)),
                ('fill_opacity', models.DecimalField(blank=True, decimal_places=1, default=1, max_digits=2, null=True)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('table', models.CharField(max_length=255)),
                ('pk_field', models.CharField(max_length=255)),
                ('geom_field', models.CharField(max_length=255)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='giscube.Category')),
                ('db_connection', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='db_connections', to='giscube.DBConnection')),
            ],
            options={
                'verbose_name': 'DataBaseLayer',
                'verbose_name_plural': 'DataBaseLayers',
            },
        ),
        migrations.CreateModel(
            name='DataBaseLayerField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(max_length=255)),
                ('alias', models.CharField(blank=True, max_length=255, null=True)),
                ('enabled', models.BooleanField(default=True)),
                ('layer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='layerserver.DataBaseLayer')),
            ],
            options={
                'verbose_name': 'Field',
                'verbose_name_plural': 'Fields',
            },
        ),
    ]
