# Generated by Django 2.1.9 on 2019-07-11 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layerserver', '0004_auto_20190708_1612'),
    ]

    operations = [
        migrations.AddField(
            model_name='databaselayer',
            name='cluster_enabled',
            field=models.BooleanField(default=False, help_text='Enable/disable cluster usage.', verbose_name='enable cluster'),
        ),
        migrations.AddField(
            model_name='databaselayer',
            name='cluster_options',
            field=models.TextField(blank=True, help_text='JSON format.', null=True, verbose_name='cluster options'),
        ),
        migrations.AddField(
            model_name='geojsonlayer',
            name='cluster_enabled',
            field=models.BooleanField(default=False, help_text='Enable/disable cluster usage.', verbose_name='enable cluster'),
        ),
        migrations.AddField(
            model_name='geojsonlayer',
            name='cluster_options',
            field=models.TextField(blank=True, help_text='JSON format.', null=True, verbose_name='cluster options'),
        )
    ]
