# Generated by Django 2.1.9 on 2019-07-11 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layerserver', '0005_auto_20190711_1325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='databaselayerfield',
            name='widget',
            field=models.CharField(choices=[('auto', 'Auto'), ('choices', 'Choices, one line per value'), ('date', 'Date'), ('datetime', 'Date time'), ('distinctvalues', 'Distinct values'), ('image', 'Image'), ('linkedfield', 'Linked Field'), ('sqlchoices', 'SQL choices')], default='auto', max_length=25, verbose_name='widget'),
        ),
    ]
