# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-25 09:53


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layerserver', '0005_dblayergroup_dblayeruser'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dblayergroup',
            options={'verbose_name': 'Group', 'verbose_name_plural': 'Groups'},
        ),
        migrations.AlterModelOptions(
            name='dblayeruser',
            options={'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.AddField(
            model_name='databaselayer',
            name='srid',
            field=models.IntegerField(default=4326),
        ),
    ]
