# Generated by Django 2.1.9 on 2019-07-11 13:41

from django.db import migrations, models
import giscube.storage
import layerserver.models


class Migration(migrations.Migration):

    dependencies = [
        ('layerserver', '0006_auto_20190711_1325'),
    ]

    operations = [
        migrations.AddField(
            model_name='databaselayer',
            name='mapfile',
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=layerserver.models.databaselayer_mapfile_upload_path,
                storage=giscube.storage.OverwriteStorage()),
        ),
        migrations.AddField(
            model_name='databaselayer',
            name='service_path',
            field=models.CharField(blank=True, max_length=255, null=True),
        )
    ]
