# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-25 13:11


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layerserver', '0006_auto_20180525_0953'),
    ]

    operations = [
        migrations.AddField(
            model_name='databaselayer',
            name='anonymous_add',
            field=models.BooleanField(default=False, verbose_name='Can add'),
        ),
        migrations.AddField(
            model_name='databaselayer',
            name='anonymous_delete',
            field=models.BooleanField(default=False, verbose_name='Can delete'),
        ),
        migrations.AddField(
            model_name='databaselayer',
            name='anonymous_update',
            field=models.BooleanField(default=False, verbose_name='Can update'),
        ),
        migrations.AddField(
            model_name='databaselayer',
            name='anonymous_view',
            field=models.BooleanField(default=False, verbose_name='Can view'),
        ),
    ]
