# Generated by Django 2.1.9 on 2019-07-12 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layerserver', '0007_auto_20190711_1541'),
    ]

    operations = [
        migrations.AddField(
            model_name='databaselayer',
            name='wms_as_reference',
            field=models.BooleanField(default=True, verbose_name='Add layer data'),
        ),
        migrations.AddField(
            model_name='databaselayerreference',
            name='refresh',
            field=models.BooleanField(default=False, verbose_name='refresh on data changes'),
        ),
    ]
