# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-29 10:51


from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qgisserver', '0009_auto_20180425_1526'),
        ('layerserver', '0007_auto_20180525_1311'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataBaseLayerReference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Reference',
                'verbose_name_plural': 'References',
            },
        ),
        migrations.AlterField(
            model_name='databaselayer',
            name='db_connection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='db_connections', to='giscube.DBConnection', verbose_name='Database connection'),
        ),
        migrations.AddField(
            model_name='databaselayerreference',
            name='layer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='layerserver.DataBaseLayer'),
        ),
        migrations.AddField(
            model_name='databaselayerreference',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qgisserver.Service'),
        ),
    ]
