# Generated by Django 2.1.9 on 2019-07-19 06:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('layerserver', '0008_auto_20190712_1112'),
    ]

    operations = [
        migrations.AddField(
            model_name='geojsonlayer',
            name='design_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='design_from_childs', to='layerserver.GeoJsonLayer', verbose_name='get design from'),
        ),
    ]
