# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-06-01 07:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layerserver', '0009_auto_20180529_1111'),
    ]

    operations = [
        migrations.AddField(
            model_name='databaselayerfield',
            name='fullsearch',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='databaselayerfield',
            name='search',
            field=models.BooleanField(default=True),
        ),
    ]
