# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-12-10 11:33


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layerserver', '0012_auto_20181207_1510'),
    ]

    operations = [
        migrations.AddField(
            model_name='databaselayerfield',
            name='values_list',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='databaselayerfield',
            name='values_list_type',
            field=models.CharField(blank=True, choices=[('flatlist', 'Flat list, one line per value'), ('sql', 'SQL')], max_length=25, null=True),
        ),
    ]
