# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2019-01-11 10:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layerserver', '0013_auto_20181210_1133'),
    ]

    operations = [
        migrations.AddField(
            model_name='databaselayerfield',
            name='type',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
