# Generated by Django 2.1.10 on 2019-12-17 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layerserver', '0013_auto_20191216_1212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='databaselayer',
            name='wms_as_reference',
            field=models.BooleanField(default=True, verbose_name='Use generated WMS as reference'),
        ),
    ]
