# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2019-01-16 11:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('layerserver', '0013_auto_20181210_1133'),
    ]

    operations = [
        migrations.RenameField(
            model_name='databaselayerfield',
            old_name='alias',
            new_name='label',
        ),
        migrations.RenameField(
            model_name='databaselayerfield',
            old_name='field',
            new_name='name',
        ),
    ]
