# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2019-02-15 08:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layerserver', '0014_auto_20190116_1110'),
    ]

    operations = [
        migrations.RenameField(
            model_name='databaselayerfield',
            old_name='values_list_type',
            new_name='widget',
        ),
        migrations.RenameField(
            model_name='databaselayerfield',
            old_name='values_list',
            new_name='widget_options',
        ),
        migrations.AlterField(
            model_name='databaselayerfield',
            name='widget',
            field=models.CharField(choices=[('auto', 'Auto'), ('choices', 'Choices, one line per value'), ('linkedfield', 'Linked Field'), ('sqlchoices', 'SQL choices')], default='auto', max_length=25),
        ),
    ]
