# Generated by Django 2.2.9 on 2020-01-15 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layerserver', '0014_auto_20191217_1229'),
    ]

    operations = [
        migrations.AddField(
            model_name='databaselayer',
            name='legend',
            field=models.TextField(blank=True, null=True, verbose_name='legend'),
        ),
        migrations.AddField(
            model_name='geojsonlayer',
            name='legend',
            field=models.TextField(blank=True, null=True, verbose_name='legend'),
        ),
    ]
