# Generated by Django 2.2.11 on 2020-04-28 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layerserver', '0016_widget'),
    ]

    operations = [
        migrations.AlterField(
            model_name='databaselayer',
            name='wms_as_reference',
            field=models.BooleanField(default=False, verbose_name='Use generated WMS as reference'),
        ),
    ]
