# Generated by Django 2.1.7 on 2019-03-05 10:11

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('layerserver', '0016_auto_20190218_0848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='databaselayer',
            name='fill_color',
            field=colorfield.fields.ColorField(blank=True, default='#FFC300', max_length=18, null=True),
        ),
        migrations.AlterField(
            model_name='databaselayer',
            name='stroke_color',
            field=colorfield.fields.ColorField(blank=True, default='#FF3333', max_length=18, null=True),
        ),
        migrations.AlterField(
            model_name='geojsonlayer',
            name='fill_color',
            field=colorfield.fields.ColorField(blank=True, default='#FFC300', max_length=18, null=True),
        ),
        migrations.AlterField(
            model_name='geojsonlayer',
            name='stroke_color',
            field=colorfield.fields.ColorField(blank=True, default='#FF3333', max_length=18, null=True),
        ),
    ]
