# Generated by Django 2.1.7 on 2019-03-19 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layerserver', '0017_auto_20190305_1011'),
    ]

    operations = [
        migrations.AddField(
            model_name='databaselayer',
            name='max_page_size',
            field=models.IntegerField(blank=True, help_text='default=1000', null=True),
        ),
        migrations.AddField(
            model_name='databaselayer',
            name='page_size',
            field=models.IntegerField(blank=True, help_text='default=50', null=True),
        ),
    ]
