# Generated by Django 2.1.7 on 2019-03-20 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layerserver', '0018_auto_20190319_1758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='databaselayer',
            name='max_page_size',
            field=models.IntegerField(blank=True, help_text='Default value is 1000', null=True),
        ),
        migrations.AlterField(
            model_name='databaselayer',
            name='page_size',
            field=models.IntegerField(blank=True, help_text='Default value is 50', null=True),
        ),
    ]
