# Generated by Django 2.1.7 on 2019-03-20 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layerserver', '0019_auto_20190320_1014'),
    ]

    operations = [
        migrations.AddField(
            model_name='geojsonlayer',
            name='headers',
            field=models.TextField(blank=True, null=True),
        ),
    ]
