# Generated by Django 2.1.7 on 2019-03-20 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layerserver', '0020_geojsonlayer_headers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='databaselayer',
            name='page_size',
            field=models.IntegerField(blank=True, help_text='Default value is 50. Value 0 disables pagination.', null=True),
        ),
    ]
