# Generated by Django 2.2.11 on 2020-05-06 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layerserver', '0021_databaselayermetadata_geojsonlayermetadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='geojsonlayer',
            name='authenticated_user_view',
            field=models.BooleanField(default=False, verbose_name='authenticated users can view'),
        ),
        migrations.AlterField(
            model_name='geojsonlayer',
            name='anonymous_view',
            field=models.BooleanField(default=False, verbose_name='anonymous users can view'),
        ),
    ]
