# Generated by Django 2.1.7 on 2019-03-20 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layerserver', '0021_auto_20190320_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geojsonlayer',
            name='url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
