# Generated by Django 2.2.11 on 2020-06-04 05:58

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layerserver', '0023_auto_20200603_0803'),
    ]

    operations = [
        migrations.AddField(
            model_name='databaselayer',
            name='data_filter',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, null=True, verbose_name='data filter'),
        ),
        migrations.AddField(
            model_name='databaselayer',
            name='data_filter_error',
            field=models.TextField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='databaselayer',
            name='data_filter_status',
            field=models.CharField(blank=True, choices=[('enabled', 'Enabled'), ('disabled', 'Error misconfigured')], editable=False, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='databaselayer',
            name='interactive',
            field=models.BooleanField(default=True, verbose_name='interactive'),
        ),
        migrations.AlterField(
            model_name='geojsonlayer',
            name='interactive',
            field=models.BooleanField(default=True, verbose_name='interactive'),
        ),
    ]
