# Generated by Django 2.1.7 on 2019-03-26 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layerserver', '0024_auto_20190326_1337'),
    ]

    operations = [
        migrations.AddField(
            model_name='databaselayer',
            name='form_fields',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='databaselayer',
            name='list_fields',
            field=models.TextField(blank=True, null=True),
        ),
    ]
