# Generated by Django 3.0.10 on 2020-09-21 08:52

from django.db import migrations, models
import django.db.models.deletion
import giscube.model_mixins
import giscube.storage


class Migration(migrations.Migration):

    dependencies = [
        ('layerserver', '0025_auto_20200824_1159'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeoJsonLayerResource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('TMS', 'TMS'), ('WMS', 'WMS'), ('document', 'Document'), ('url', 'URL')], max_length=12, verbose_name='type')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('title', models.CharField(blank=True, max_length=100, null=True, verbose_name='title')),
                ('path', models.CharField(blank=True, max_length=255, null=True, verbose_name='path')),
                ('url', models.CharField(blank=True, max_length=255, null=True, verbose_name='url')),
                ('file', models.FileField(blank=True, max_length=255, null=True, storage=giscube.storage.OverwriteStorage(), upload_to=giscube.model_mixins.resource_upload_to, verbose_name='file')),
                ('layers', models.CharField(blank=True, max_length=255, null=True, verbose_name='layers')),
                ('projection', models.IntegerField(blank=True, help_text='EPSG code', null=True, verbose_name='projection')),
                ('getfeatureinfo_support', models.BooleanField(default=True, verbose_name='WMS GetFeatureInfo support')),
                ('single_image', models.BooleanField(default=False, verbose_name='use single image')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='layerserver.GeoJsonLayer')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DataBaseLayerResource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('TMS', 'TMS'), ('WMS', 'WMS'), ('document', 'Document'), ('url', 'URL')], max_length=12, verbose_name='type')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('title', models.CharField(blank=True, max_length=100, null=True, verbose_name='title')),
                ('path', models.CharField(blank=True, max_length=255, null=True, verbose_name='path')),
                ('url', models.CharField(blank=True, max_length=255, null=True, verbose_name='url')),
                ('file', models.FileField(blank=True, max_length=255, null=True, storage=giscube.storage.OverwriteStorage(), upload_to=giscube.model_mixins.resource_upload_to, verbose_name='file')),
                ('layers', models.CharField(blank=True, max_length=255, null=True, verbose_name='layers')),
                ('projection', models.IntegerField(blank=True, help_text='EPSG code', null=True, verbose_name='projection')),
                ('getfeatureinfo_support', models.BooleanField(default=True, verbose_name='WMS GetFeatureInfo support')),
                ('single_image', models.BooleanField(default=False, verbose_name='use single image')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='layerserver.DataBaseLayer')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
