# Generated by Django 3.0.10 on 2020-09-21 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layerserver', '0026_databaselayerresource_geojsonlayerresource'),
    ]

    operations = [
        migrations.AddField(
            model_name='databaselayerresource',
            name='downloadable',
            field=models.BooleanField(default=False, verbose_name='downloadable'),
        ),
        migrations.AddField(
            model_name='geojsonlayerresource',
            name='downloadable',
            field=models.BooleanField(default=False, verbose_name='downloadable'),
        ),
    ]
