# Generated by Django 2.1.7 on 2019-04-01 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layerserver', '0026_auto_20190326_1356'),
    ]

    operations = [
        migrations.AddField(
            model_name='databaselayerfield',
            name='readonly',
            field=models.BooleanField(default=False),
        ),
    ]
