# Generated by Django 3.0.10 on 2020-11-11 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layerserver', '0027_auto_20200921_1501'),
    ]

    operations = [
        migrations.AddField(
            model_name='databaselayerresource',
            name='content_type',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='content type'),
        ),
        migrations.AddField(
            model_name='geojsonlayerresource',
            name='content_type',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='content type'),
        ),
    ]
