# Generated by Django 2.1.7 on 2019-04-04 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layerserver', '0027_databaselayerfield_readonly'),
    ]

    operations = [
        migrations.AddField(
            model_name='databaselayer',
            name='allow_page_size_0',
            field=models.BooleanField(default=False, verbose_name='Allow page_size=0 (Disables pagination)'),
        )
    ]
