# Generated by Django 2.1.7 on 2019-04-06 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layerserver', '0028_auto_20190404_2030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='databaselayer',
            name='geom_field',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='databaselayer',
            name='pk_field',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
