# Generated by Django 2.2.17 on 2020-11-23 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layerserver', '0028_auto_20201111_0745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='databaselayerresource',
            name='content_type',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='format'),
        ),
        migrations.AlterField(
            model_name='geojsonlayerresource',
            name='content_type',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='format'),
        ),
    ]
