# Generated by Django 2.2.17 on 2020-12-21 13:31

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layerserver', '0029_auto_20201123_1354'),
    ]

    operations = [
        migrations.AddField(
            model_name='dblayergroup',
            name='data_filter',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, null=True, verbose_name='data filter'),
        ),
        migrations.AddField(
            model_name='dblayergroup',
            name='data_filter_error',
            field=models.TextField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='dblayergroup',
            name='data_filter_status',
            field=models.CharField(blank=True, choices=[('enabled', 'Enabled'), ('disabled', 'Error misconfigured')], editable=False, max_length=50, null=True),
        ),
    ]
