# Generated by Django 2.1.7 on 2019-04-11 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layerserver', '0029_auto_20190406_1352'),
    ]

    operations = [
        migrations.AddField(
            model_name='databaselayer',
            name='icon',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='databaselayer',
            name='icon_color',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='databaselayer',
            name='icon_type',
            field=models.CharField(blank=True, choices=[('fa', 'fa'), ('img', 'img')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='databaselayer',
            name='marker_color',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='geojsonlayer',
            name='icon',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='geojsonlayer',
            name='icon_color',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='geojsonlayer',
            name='icon_type',
            field=models.CharField(blank=True, choices=[('fa', 'fa'), ('img', 'img')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='geojsonlayer',
            name='marker_color',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='databaselayer',
            name='fill_color',
            field=models.CharField(blank=True, default='#FFC300', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='databaselayer',
            name='shapetype',
            field=models.CharField(blank=True, choices=[('marker', 'Marker'), ('line', 'Line'), ('polygon', 'Polygon'), ('circle', 'Circle')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='databaselayer',
            name='stroke_color',
            field=models.CharField(blank=True, default='#FF3333', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='geojsonlayer',
            name='fill_color',
            field=models.CharField(blank=True, default='#FFC300', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='geojsonlayer',
            name='shapetype',
            field=models.CharField(blank=True, choices=[('marker', 'Marker'), ('line', 'Line'), ('polygon', 'Polygon'), ('circle', 'Circle')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='geojsonlayer',
            name='stroke_color',
            field=models.CharField(blank=True, default='#FF3333', max_length=50, null=True),
        ),
    ]
