# Generated by Django 2.1.7 on 2019-04-16 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layerserver', '0030_auto_20190411_0621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='databaselayer',
            name='fill_opacity',
            field=models.CharField(blank=True, default='1', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='databaselayer',
            name='shape_radius',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='databaselayer',
            name='stroke_dash_array',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='databaselayer',
            name='stroke_width',
            field=models.CharField(blank=True, default='1', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='geojsonlayer',
            name='fill_opacity',
            field=models.CharField(blank=True, default='1', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='geojsonlayer',
            name='shape_radius',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='geojsonlayer',
            name='stroke_dash_array',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='geojsonlayer',
            name='stroke_width',
            field=models.CharField(blank=True, default='1', max_length=50, null=True),
        ),
    ]
