# Generated by Django 2.1.7 on 2019-04-17 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('layerserver', '0031_auto_20190416_1503'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataBaseLayerStyleRule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shape_radius', models.CharField(blank=True, max_length=50, null=True)),
                ('stroke_color', models.CharField(blank=True, default='#FF3333', max_length=50, null=True)),
                ('stroke_width', models.CharField(blank=True, default='1', max_length=50, null=True)),
                ('stroke_dash_array', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('fill_color', models.CharField(blank=True, default='#FFC300', max_length=50, null=True)),
                ('fill_opacity', models.CharField(blank=True, default='1', max_length=50, null=True)),
                ('marker_color', models.CharField(blank=True, max_length=50, null=True)),
                ('icon_type', models.CharField(blank=True, choices=[('fa', 'fa'), ('img', 'img')], max_length=100, null=True)),
                ('icon', models.CharField(blank=True, max_length=255, null=True)),
                ('icon_color', models.CharField(blank=True, max_length=50, null=True)),
                ('field', models.CharField(max_length=50)),
                ('comparator', models.CharField(choices=[('=', '='), ('!=', '!='), ('>', '>'), ('>=', '>='), ('<', '<'), ('<=', '<=')], max_length=3)),
                ('value', models.CharField(max_length=255)),
                ('order', models.PositiveIntegerField(blank=True, null=True)),
                ('layer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='layerserver.DataBaseLayer')),
            ],
            options={
                'ordering': ('layer', 'order'),
                'verbose_name_plural': 'Style rules',
                'verbose_name': 'Style rule',
            },
        ),
        migrations.CreateModel(
            name='GeoJsonLayerStyleRule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shape_radius', models.CharField(blank=True, max_length=50, null=True)),
                ('stroke_color', models.CharField(blank=True, default='#FF3333', max_length=50, null=True)),
                ('stroke_width', models.CharField(blank=True, default='1', max_length=50, null=True)),
                ('stroke_dash_array', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('fill_color', models.CharField(blank=True, default='#FFC300', max_length=50, null=True)),
                ('fill_opacity', models.CharField(blank=True, default='1', max_length=50, null=True)),
                ('marker_color', models.CharField(blank=True, max_length=50, null=True)),
                ('icon_type', models.CharField(blank=True, choices=[('fa', 'fa'), ('img', 'img')], max_length=100, null=True)),
                ('icon', models.CharField(blank=True, max_length=255, null=True)),
                ('icon_color', models.CharField(blank=True, max_length=50, null=True)),
                ('field', models.CharField(max_length=50)),
                ('comparator', models.CharField(choices=[('=', '='), ('!=', '!='), ('>', '>'), ('>=', '>='), ('<', '<'), ('<=', '<=')], max_length=3)),
                ('value', models.CharField(blank=True, max_length=255, null=True)),
                ('order', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ('layer', 'order'),
                'verbose_name_plural': 'Style rules',
                'verbose_name': 'Style rule',
            },
        ),
        migrations.AddField(
            model_name='geojsonlayerstylerule',
            name='layer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='layerserver.GeoJsonLayer'),
        ),
    ]
