# Generated by Django 2.1.7 on 2019-04-17 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layerserver', '0032_auto_20190417_1308'),
    ]

    operations = [
        migrations.AddField(
            model_name='geojsonlayer',
            name='fields',
            field=models.TextField(blank=True, null=True),
        ),
    ]
