# Generated by Django 3.2.17 on 2024-10-10 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layerserver', '0033_auto_20230314_1233'),
    ]

    operations = [
        migrations.AddField(
            model_name='geojsonlayer',
            name='filtered_fields',
            field=models.TextField(blank=True, null=True, verbose_name='filtered fields'),
        ),
    ]
