# Generated by Django 2.1.7 on 2019-04-24 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layerserver', '0033_geojsonlayer_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='databaselayerfield',
            name='blank',
            field=models.BooleanField(default=True),
        ),
    ]
