# Generated by Django 3.2.17 on 2025-07-03 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layerserver', '0034_geojsonlayer_filtered_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='databaselayer',
            name='catalog_color',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='catalog color'),
        ),
        migrations.AddField(
            model_name='geojsonfilter',
            name='catalog_color',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='catalog color'),
        ),
        migrations.AddField(
            model_name='geojsonlayer',
            name='catalog_color',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='catalog color'),
        ),
    ]
