# Generated by Django 2.1.7 on 2019-04-27 06:20

from django.db import migrations, models


def update_name(apps, schema_editor):
    DataBaseLayer = apps.get_model('layerserver', 'DataBaseLayer')
    DataBaseLayer.objects.all().update(name=models.F('slug'))


def reverse_func(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('layerserver', '0034_databaselayerfield_blank'),
    ]

    operations = [
        migrations.RunPython(update_name, reverse_func),
        migrations.RemoveField(
            model_name='databaselayer',
            name='slug',
        ),
        migrations.AlterField(
            model_name='databaselayer',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
