# Generated by Django 3.2.17 on 2025-09-03 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qgisserver', '0036_auto_20250703_1313'),
        ('layerserver', '0035_auto_20250703_1408'),
    ]

    operations = [
        migrations.AddField(
            model_name='databaselayer',
            name='additional_layer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='databaselayers', to='qgisserver.service', verbose_name='Additional layer'),
        ),
    ]
