# Generated by Django 2.1.7 on 2019-05-07 09:14

from django.db import migrations, models
import layerserver.models


class Migration(migrations.Migration):

    dependencies = [
        ('layerserver', '0035_auto_20190427_0620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='databaselayer',
            name='allow_page_size_0',
            field=models.BooleanField(default=False, verbose_name='Allow page size=0 (Disables pagination)'),
        ),
        migrations.AlterField(
            model_name='databaselayer',
            name='form_fields',
            field=models.TextField(blank=True, null=True, verbose_name='form fields'),
        ),
        migrations.AlterField(
            model_name='databaselayer',
            name='geom_field',
            field=models.CharField(max_length=255, verbose_name='geom field'),
        ),
        migrations.AlterField(
            model_name='databaselayer',
            name='list_fields',
            field=models.TextField(blank=True, null=True, verbose_name='list fields'),
        ),
        migrations.AlterField(
            model_name='databaselayer',
            name='max_page_size',
            field=models.IntegerField(blank=True, help_text='Default value is 1000', null=True, verbose_name='maximum page size'),
        ),
        migrations.AlterField(
            model_name='databaselayer',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='databaselayer',
            name='page_size',
            field=models.IntegerField(blank=True, help_text='Default value is 50. Value 0 disables pagination.', null=True, verbose_name='page size'),
        ),
        migrations.AlterField(
            model_name='databaselayer',
            name='pk_field',
            field=models.CharField(blank=True, max_length=255, verbose_name='pk field'),
        ),
        migrations.AlterField(
            model_name='databaselayer',
            name='shapetype',
            field=models.CharField(blank=True, choices=[('marker', 'Marker'), ('line', 'Line'), ('polygon', 'Polygon'), ('circle', 'Circle'), ('image', 'Image')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='databaselayer',
            name='srid',
            field=models.IntegerField(default=4326, verbose_name='srid'),
        ),
        migrations.AlterField(
            model_name='databaselayer',
            name='table',
            field=models.CharField(max_length=255, verbose_name='table'),
        ),
        migrations.AlterField(
            model_name='databaselayerfield',
            name='blank',
            field=models.BooleanField(default=True, verbose_name='blank'),
        ),
        migrations.AlterField(
            model_name='databaselayerfield',
            name='enabled',
            field=models.BooleanField(default=True, verbose_name='enabled'),
        ),
        migrations.AlterField(
            model_name='databaselayerfield',
            name='fullsearch',
            field=models.BooleanField(default=True, verbose_name='full search'),
        ),
        migrations.AlterField(
            model_name='databaselayerfield',
            name='label',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='label'),
        ),
        migrations.AlterField(
            model_name='databaselayerfield',
            name='name',
            field=models.CharField(max_length=255, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='databaselayerfield',
            name='readonly',
            field=models.BooleanField(default=False, verbose_name='readonly'),
        ),
        migrations.AlterField(
            model_name='databaselayerfield',
            name='search',
            field=models.BooleanField(default=True, verbose_name='search'),
        ),
        migrations.AlterField(
            model_name='databaselayerfield',
            name='widget',
            field=models.CharField(choices=[('auto', 'Auto'), ('choices', 'Choices, one line per value'), ('date', 'Date'), ('image', 'Image'), ('linkedfield', 'Linked Field'), ('sqlchoices', 'SQL choices')], default='auto', max_length=25, verbose_name='widget'),
        ),
        migrations.AlterField(
            model_name='databaselayerfield',
            name='widget_options',
            field=models.TextField(blank=True, null=True, verbose_name='widget options'),
        ),
        migrations.AlterField(
            model_name='databaselayerstylerule',
            name='comparator',
            field=models.CharField(choices=[('=', '='), ('!=', '!='), ('>', '>'), ('>=', '>='), ('<', '<'), ('<=', '<=')], max_length=3, verbose_name='comparator'),
        ),
        migrations.AlterField(
            model_name='databaselayerstylerule',
            name='field',
            field=models.CharField(max_length=50, verbose_name='field'),
        ),
        migrations.AlterField(
            model_name='databaselayerstylerule',
            name='order',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='order'),
        ),
        migrations.AlterField(
            model_name='databaselayerstylerule',
            name='value',
            field=models.CharField(max_length=255, verbose_name='value'),
        ),
        migrations.AlterField(
            model_name='geojsonlayer',
            name='cache_time',
            field=models.IntegerField(blank=True, help_text='In seconds', null=True, verbose_name='cache time'),
        ),
        migrations.AlterField(
            model_name='geojsonlayer',
            name='data_file',
            field=models.FileField(blank=True, null=True, upload_to=layerserver.models.geojsonlayer_upload_path, verbose_name='data file'),
        ),
        migrations.AlterField(
            model_name='geojsonlayer',
            name='generated_on',
            field=models.DateTimeField(blank=True, null=True, verbose_name='generated on'),
        ),
        migrations.AlterField(
            model_name='geojsonlayer',
            name='headers',
            field=models.TextField(blank=True, null=True, verbose_name='headers'),
        ),
        migrations.AlterField(
            model_name='geojsonlayer',
            name='last_fetch_on',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last fetch on'),
        ),
        migrations.AlterField(
            model_name='geojsonlayer',
            name='service_path',
            field=models.CharField(max_length=255, verbose_name='service path'),
        ),
        migrations.AlterField(
            model_name='geojsonlayer',
            name='shapetype',
            field=models.CharField(blank=True, choices=[('marker', 'Marker'), ('line', 'Line'), ('polygon', 'Polygon'), ('circle', 'Circle'), ('image', 'Image')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='geojsonlayer',
            name='url',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='url'),
        ),
        migrations.AlterField(
            model_name='geojsonlayer',
            name='visibility',
            field=models.CharField(choices=[('private', 'Private'), ('public', 'Public')], default='private', help_text="visibility='Private' restricts usage to authenticated users", max_length=10, verbose_name='visibility'),
        ),
        migrations.AlterField(
            model_name='geojsonlayerstylerule',
            name='comparator',
            field=models.CharField(choices=[('=', '='), ('!=', '!='), ('>', '>'), ('>=', '>='), ('<', '<'), ('<=', '<=')], max_length=3, verbose_name='comparator'),
        ),
        migrations.AlterField(
            model_name='geojsonlayerstylerule',
            name='field',
            field=models.CharField(max_length=50, verbose_name='field'),
        ),
        migrations.AlterField(
            model_name='geojsonlayerstylerule',
            name='order',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='order'),
        ),
        migrations.AlterField(
            model_name='geojsonlayerstylerule',
            name='value',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='value'),
        ),
        migrations.AlterField(
            model_name='databaselayer',
            name='shapetype',
            field=models.CharField(blank=True, choices=[('marker', 'Marker'), ('line', 'Line'), ('polygon', 'Polygon'), ('circle', 'Circle'), ('image', 'Image')], max_length=20, null=True, verbose_name='Shape Type'),
        ),
        migrations.AlterField(
            model_name='geojsonlayer',
            name='shapetype',
            field=models.CharField(blank=True, choices=[('marker', 'Marker'), ('line', 'Line'), ('polygon', 'Polygon'), ('circle', 'Circle'), ('image', 'Image')], max_length=20, null=True, verbose_name='Shape Type'),
        ),
    ]
