# Generated by Django 2.1.7 on 2019-05-07 09:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import layerserver.models


class Migration(migrations.Migration):

    dependencies = [
        ('layerserver', '0035_auto_20190427_0620'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='databaselayerfield',
            options={'ordering': ['layer', 'name'], 'verbose_name': 'Camp', 'verbose_name_plural': 'Camps'},
        ),
        migrations.AlterModelOptions(
            name='databaselayerreference',
            options={'verbose_name': 'Referència', 'verbose_name_plural': 'Referències'},
        ),
        migrations.AlterModelOptions(
            name='databaselayerstylerule',
            options={'ordering': ('layer', 'order'), 'verbose_name': "Regla d'estil", 'verbose_name_plural': "Regles d'estil"},
        ),
        migrations.AlterModelOptions(
            name='dblayergroup',
            options={'verbose_name': 'Grup', 'verbose_name_plural': 'Grups'},
        ),
        migrations.AlterModelOptions(
            name='dblayeruser',
            options={'verbose_name': 'Usuari', 'verbose_name_plural': 'Usuaris'},
        ),
        migrations.AlterModelOptions(
            name='geojsonlayer',
            options={'verbose_name': 'Capa GeoJSON', 'verbose_name_plural': 'Capes GeoJSON'},
        ),
        migrations.AlterModelOptions(
            name='geojsonlayerstylerule',
            options={'ordering': ('layer', 'order'), 'verbose_name': "Regla d'estil", 'verbose_name_plural': "Regles d'estil"},
        ),
        migrations.AlterField(
            model_name='databaselayer',
            name='allow_page_size_0',
            field=models.BooleanField(default=False, verbose_name='Permetre mida de la pàgina=0 (Desactiva la paginació)'),
        ),
        migrations.AlterField(
            model_name='databaselayer',
            name='anonymous_add',
            field=models.BooleanField(default=False, verbose_name='Permet afegir'),
        ),
        migrations.AlterField(
            model_name='databaselayer',
            name='anonymous_delete',
            field=models.BooleanField(default=False, verbose_name='Permet eliminar'),
        ),
        migrations.AlterField(
            model_name='databaselayer',
            name='anonymous_update',
            field=models.BooleanField(default=False, verbose_name='Permet actualitzar'),
        ),
        migrations.AlterField(
            model_name='databaselayer',
            name='anonymous_view',
            field=models.BooleanField(default=False, verbose_name='Permet veure'),
        ),
        migrations.AlterField(
            model_name='databaselayer',
            name='form_fields',
            field=models.TextField(blank=True, null=True, verbose_name='Camps al formulari'),
        ),
        migrations.AlterField(
            model_name='databaselayer',
            name='geom_field',
            field=models.CharField(max_length=255, verbose_name='camp amb geometria'),
        ),
        migrations.AlterField(
            model_name='databaselayer',
            name='list_fields',
            field=models.TextField(blank=True, null=True, verbose_name='Camps al llistat'),
        ),
        migrations.AlterField(
            model_name='databaselayer',
            name='max_page_size',
            field=models.IntegerField(blank=True, help_text='El valor per defecte és 1000', null=True, verbose_name='valor màxim de mida de la pàgina'),
        ),
        migrations.AlterField(
            model_name='databaselayer',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='nom'),
        ),
        migrations.AlterField(
            model_name='databaselayer',
            name='page_size',
            field=models.IntegerField(blank=True, help_text='El valor per defecte és 50. Valor 0 desactiva la paginació.', null=True, verbose_name='mida de la pàgina'),
        ),
        migrations.AlterField(
            model_name='databaselayer',
            name='pk_field',
            field=models.CharField(blank=True, max_length=255, verbose_name='clau primària'),
        ),
        migrations.AlterField(
            model_name='databaselayer',
            name='shapetype',
            field=models.CharField(blank=True, choices=[('marker', 'Marcador'), ('line', 'Línia'), ('polygon', 'Polígon'), ('circle', 'Cercle'), ('image', 'Imatge')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='databaselayer',
            name='srid',
            field=models.IntegerField(default=4326, verbose_name='srid'),
        ),
        migrations.AlterField(
            model_name='databaselayer',
            name='table',
            field=models.CharField(max_length=255, verbose_name='taula'),
        ),
        migrations.AlterField(
            model_name='databaselayerfield',
            name='blank',
            field=models.BooleanField(default=True, verbose_name='blanc'),
        ),
        migrations.AlterField(
            model_name='databaselayerfield',
            name='enabled',
            field=models.BooleanField(default=True, verbose_name='actiu'),
        ),
        migrations.AlterField(
            model_name='databaselayerfield',
            name='fullsearch',
            field=models.BooleanField(default=True, verbose_name='activa cerca completa'),
        ),
        migrations.AlterField(
            model_name='databaselayerfield',
            name='label',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Etiqueta'),
        ),
        migrations.AlterField(
            model_name='databaselayerfield',
            name='name',
            field=models.CharField(max_length=255, verbose_name='nom'),
        ),
        migrations.AlterField(
            model_name='databaselayerfield',
            name='readonly',
            field=models.BooleanField(default=False, verbose_name='mode lectura'),
        ),
        migrations.AlterField(
            model_name='databaselayerfield',
            name='search',
            field=models.BooleanField(default=True, verbose_name='cercable'),
        ),
        migrations.AlterField(
            model_name='databaselayerfield',
            name='widget',
            field=models.CharField(choices=[('auto', 'Automàtic'), ('choices', 'Escollir, un valor per línia'), ('date', 'Data'), ('image', 'Imatge'), ('linkedfield', 'Camp enllaçat'), ('sqlchoices', 'Escollit mitjançant consulta SQL')], default='auto', max_length=25, verbose_name='srid'),
        ),
        migrations.AlterField(
            model_name='databaselayerfield',
            name='widget_options',
            field=models.TextField(blank=True, null=True, verbose_name='srid'),
        ),
        migrations.AlterField(
            model_name='databaselayerstylerule',
            name='comparator',
            field=models.CharField(choices=[('=', '='), ('!=', '!='), ('>', '>'), ('>=', '>='), ('<', '<'), ('<=', '<=')], max_length=3, verbose_name='comparador'),
        ),
        migrations.AlterField(
            model_name='databaselayerstylerule',
            name='field',
            field=models.CharField(max_length=50, verbose_name='field'),
        ),
        migrations.AlterField(
            model_name='databaselayerstylerule',
            name='order',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='ordre'),
        ),
        migrations.AlterField(
            model_name='databaselayerstylerule',
            name='value',
            field=models.CharField(max_length=255, verbose_name='valor'),
        ),
        migrations.AlterField(
            model_name='dblayergroup',
            name='can_add',
            field=models.BooleanField(default=True, verbose_name='Permet afegir'),
        ),
        migrations.AlterField(
            model_name='dblayergroup',
            name='can_delete',
            field=models.BooleanField(default=True, verbose_name='Permet eliminar'),
        ),
        migrations.AlterField(
            model_name='dblayergroup',
            name='can_update',
            field=models.BooleanField(default=True, verbose_name='Permet actualitzar'),
        ),
        migrations.AlterField(
            model_name='dblayergroup',
            name='can_view',
            field=models.BooleanField(default=True, verbose_name='Permet veure'),
        ),
        migrations.AlterField(
            model_name='dblayergroup',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.Group', verbose_name='Grup'),
        ),
        migrations.AlterField(
            model_name='dblayeruser',
            name='can_add',
            field=models.BooleanField(default=True, verbose_name='Permet afegir'),
        ),
        migrations.AlterField(
            model_name='dblayeruser',
            name='can_delete',
            field=models.BooleanField(default=True, verbose_name='Permet eliminar'),
        ),
        migrations.AlterField(
            model_name='dblayeruser',
            name='can_update',
            field=models.BooleanField(default=True, verbose_name='Permet actualitzar'),
        ),
        migrations.AlterField(
            model_name='dblayeruser',
            name='can_view',
            field=models.BooleanField(default=True, verbose_name='Permet veure'),
        ),
        migrations.AlterField(
            model_name='dblayeruser',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuari'),
        ),
        migrations.AlterField(
            model_name='geojsonlayer',
            name='cache_time',
            field=models.IntegerField(blank=True, help_text='In seconds', null=True, verbose_name="temps de 'cache'"),
        ),
        migrations.AlterField(
            model_name='geojsonlayer',
            name='data_file',
            field=models.FileField(blank=True, null=True, upload_to=layerserver.models.geojsonlayer_upload_path, verbose_name='data file'),
        ),
        migrations.AlterField(
            model_name='geojsonlayer',
            name='generated_on',
            field=models.DateTimeField(blank=True, null=True, verbose_name='data generació'),
        ),
        migrations.AlterField(
            model_name='geojsonlayer',
            name='headers',
            field=models.TextField(blank=True, null=True, verbose_name='capçaleres'),
        ),
        migrations.AlterField(
            model_name='geojsonlayer',
            name='last_fetch_on',
            field=models.DateTimeField(blank=True, null=True, verbose_name='data descàrrega'),
        ),
        migrations.AlterField(
            model_name='geojsonlayer',
            name='service_path',
            field=models.CharField(max_length=255, verbose_name='service path'),
        ),
        migrations.AlterField(
            model_name='geojsonlayer',
            name='shapetype',
            field=models.CharField(blank=True, choices=[('marker', 'Marcador'), ('line', 'Línia'), ('polygon', 'Polígon'), ('circle', 'Cercle'), ('image', 'Imatge')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='geojsonlayer',
            name='url',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='url'),
        ),
        migrations.AlterField(
            model_name='geojsonlayer',
            name='visibility',
            field=models.CharField(choices=[('private', 'Privat'), ('public', 'Públic')], default='private', help_text="visibilitat='Privat' restringeix l'ús només als usuaris autenticats", max_length=10, verbose_name='visibilitat'),
        ),
        migrations.AlterField(
            model_name='geojsonlayerstylerule',
            name='comparator',
            field=models.CharField(choices=[('=', '='), ('!=', '!='), ('>', '>'), ('>=', '>='), ('<', '<'), ('<=', '<=')], max_length=3, verbose_name='comparador'),
        ),
        migrations.AlterField(
            model_name='geojsonlayerstylerule',
            name='field',
            field=models.CharField(max_length=50, verbose_name='field'),
        ),
        migrations.AlterField(
            model_name='geojsonlayerstylerule',
            name='order',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='ordre'),
        ),
        migrations.AlterField(
            model_name='geojsonlayerstylerule',
            name='value',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='valor'),
        ),
    ]
