# Generated by Django 2.1.7 on 2019-05-14 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layerserver', '0036_auto_20190507_0914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='databaselayer',
            name='geom_field',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='geom field'),
        ),
        migrations.AlterField(
            model_name='databaselayer',
            name='srid',
            field=models.IntegerField(blank=True, default=4326, null=True, verbose_name='srid'),
        ),
    ]
