# Generated by Django 3.2.17 on 2026-05-11 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('giscube', '0033_dataset_additional_categories'),
        ('layerserver', '0036_databaselayer_additional_layer'),
    ]

    operations = [
        migrations.AddField(
            model_name='databaselayer',
            name='additional_categories',
            field=models.ManyToManyField(blank=True, related_name='layerserver_databaselayer_categories', to='giscube.Category', verbose_name='additional categories'),
        ),
        migrations.AddField(
            model_name='geojsonlayer',
            name='additional_categories',
            field=models.ManyToManyField(blank=True, related_name='layerserver_geojsonlayer_categories', to='giscube.Category', verbose_name='additional categories'),
        ),
        migrations.AlterField(
            model_name='databaselayer',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='layerserver_databaselayer_category', to='giscube.category', verbose_name='category'),
        ),
        migrations.AlterField(
            model_name='geojsonlayer',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='layerserver_geojsonlayer_category', to='giscube.category', verbose_name='category'),
        ),
    ]
