# Generated by Django 3.2.17 on 2026-03-30 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layerserver', '0036_databaselayer_additional_layer'),
    ]

    operations = [
        migrations.AddField(
            model_name='databaselayerresource',
            name='style',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='style'),
        ),
        migrations.AddField(
            model_name='databaselayerresource',
            name='tile_matrix_set',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='tile matrix set'),
        ),
        migrations.AddField(
            model_name='geojsonlayerresource',
            name='style',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='style'),
        ),
        migrations.AddField(
            model_name='geojsonlayerresource',
            name='tile_matrix_set',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='tile matrix set'),
        ),
        migrations.AlterField(
            model_name='databaselayerresource',
            name='type',
            field=models.CharField(choices=[('TMS', 'TMS'), ('WMS', 'WMS'), ('WMTS', 'WMTS'), ('document', 'Document'), ('url', 'URL')], max_length=12, verbose_name='type'),
        ),
        migrations.AlterField(
            model_name='geojsonlayerresource',
            name='type',
            field=models.CharField(choices=[('TMS', 'TMS'), ('WMS', 'WMS'), ('WMTS', 'WMTS'), ('document', 'Document'), ('url', 'URL')], max_length=12, verbose_name='type'),
        ),
    ]
