# Generated by Django 2.1.7 on 2019-05-16 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layerserver', '0037_auto_20190514_0812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='databaselayer',
            name='srid',
            field=models.IntegerField(blank=True, null=True, verbose_name='srid'),
        ),
    ]
