# Generated by Django 3.2.17 on 2026-07-14 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layerserver', '0037_auto_20260511_1703'),
    ]

    operations = [
        migrations.AddField(
            model_name='geojsonlayer',
            name='overlapping_geometries',
            field=models.BooleanField(default=False, verbose_name='overlapping geometries'),
        ),
    ]
