# Generated by Django 2.1.7 on 2019-05-16 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('layerserver', '0038_auto_20190516_0814'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataBaseLayerVirtualField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('label', models.CharField(blank=True, max_length=255, null=True, verbose_name='label')),
                ('enabled', models.BooleanField(default=True, verbose_name='enabled')),
                ('widget', models.CharField(choices=[('relation1n', '1:N Relation'), ('linkedfield', 'Linked Field')], max_length=25, verbose_name='widget')),
                ('widget_options', models.TextField(blank=True, null=True, verbose_name='widget options')),
                ('layer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='virtual_fields', to='layerserver.DataBaseLayer')),
            ],
            options={
                'ordering': ['layer', 'name'],
                'verbose_name_plural': 'Virtual Fields',
                'verbose_name': 'Virtual Field',
            },
        ),
        migrations.AlterField(
            model_name='databaselayerfield',
            name='widget',
            field=models.CharField(choices=[('auto', 'Auto'), ('choices', 'Choices, one line per value'), ('date', 'Date'), ('datetime', 'Date time'), ('image', 'Image'), ('linkedfield', 'Linked Field'), ('sqlchoices', 'SQL choices')], default='auto', max_length=25, verbose_name='widget'),
        ),
    ]
