# Generated by Django 2.1.7 on 2019-05-21 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layerserver', '0039_auto_20190516_1036'),
    ]

    operations = [
        migrations.AddField(
            model_name='geojsonlayer',
            name='max_outdated_time',
            field=models.PositiveIntegerField(blank=True, help_text='Maximum outdated time in seconds for the cache file', null=True, verbose_name='maximum outdated time'),
        ),
        migrations.AlterField(
            model_name='geojsonlayer',
            name='cache_time',
            field=models.PositiveIntegerField(blank=True, help_text='time in seconds where the file is served from cache', null=True, verbose_name='cache time'),
        ),
    ]
