# Generated by Django 2.1.7 on 2019-06-12 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layerserver', '0040_auto_20190521_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geojsonlayer',
            name='cache_time',
            field=models.PositiveIntegerField(blank=True, help_text='Time in seconds where the file is served from cache', null=True, verbose_name='cache time'),
        ),
    ]
