# Generated by Django 2.2.17 on 2021-06-10 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layerserver', '0041_auto_20190612_1532'),
    ]

    operations = [
        migrations.AddField(
            model_name='databaselayerresource',
            name='layer_list',
            field=models.TextField(blank=True, null=True, verbose_name='layer_list'),
        ),
        migrations.AddField(
            model_name='databaselayerresource',
            name='separate_layers',
            field=models.BooleanField(default=False, verbose_name='use separate layers'),
        ),
        migrations.AddField(
            model_name='geojsonlayerresource',
            name='layer_list',
            field=models.TextField(blank=True, null=True, verbose_name='layer_list'),
        ),
        migrations.AddField(
            model_name='geojsonlayerresource',
            name='separate_layers',
            field=models.BooleanField(default=False, verbose_name='use separate layers'),
        ),
    ]
