# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-27 18:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geoportal', '0002_dataset_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='dataset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='geoportal.Dataset'),
        ),
    ]
