# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-23 13:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geoportal', '0005_auto_20180410_1217'),
        ('imageserver', '0008_auto_20180423_1322'),
        ('qgisserver', '0008_auto_20180423_1322'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='parent',
        ),
        migrations.AlterField(
            model_name='dataset',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='giscube.Category'),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
