# Generated by Django 2.1.7 on 2019-03-05 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geoportal', '0006_auto_20180423_1348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='projection',
            field=models.IntegerField(help_text='EPSG code'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='type',
            field=models.CharField(choices=[('TMS', 'TMS'), ('WMS', 'WMS')], max_length=12),
        ),
    ]
