# Generated by Django 2.1.7 on 2019-05-07 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geoportal', '0009_dataset_options'),
    ]

    operations = []
