# Generated by Django 2.1.7 on 2019-05-07 09:14

from django.db import migrations, models
import giscube.validators


class Migration(migrations.Migration):

    dependencies = [
        ('geoportal', '0009_dataset_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataset',
            name='options',
            field=models.TextField(blank=True, help_text='json format. Ex: {"maxZoom": 20}', null=True, validators=[giscube.validators.validate_options_json_format], verbose_name='opcions'),
        ),
    ]
