# Generated by Django 2.1.10 on 2019-12-11 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geoportal', '0010_auto_20190507_0914'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='getfeatureinfo_support',
            field=models.BooleanField(default=True, verbose_name='WMS GetFeatureInfo support'),
        ),
        migrations.AddField(
            model_name='resource',
            name='single_image',
            field=models.BooleanField(default=False, verbose_name='Use single image'),
        ),
    ]
