# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-23 12:50
from __future__ import unicode_literals

from django.db import migrations

class Migration(migrations.Migration):

    dependencies = [
        ('giscube', '0001_initial'),
    ]
    sql0 = '''
    INSERT INTO giscube_category SELECT * FROM geoportal_category;
    '''
    sql1 = '''
    SELECT setval('giscube_category_id_seq', max(id))
    FROM geoportal_category;
    '''
    operations = [
        # migrations.RunPython(forwards_func, reverse_func),
        migrations.RunSQL(sql0),
        migrations.RunSQL(sql1),
    ]
