# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-23 12:50


from django.db import connection, migrations


class Migration(migrations.Migration):

    dependencies = [
        ('giscube', '0001_initial'),
    ]

    operations = []
