# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-21 12:57


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giscube', '0003_dbconnection'),
    ]

    operations = [
        migrations.AddField(
            model_name='dbconnection',
            name='alias',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
