# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-29 10:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('giscube', '0004_dbconnection_alias'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dbconnection',
            options={'verbose_name': 'Database connection', 'verbose_name_plural': 'Database connections'},
        ),
    ]
