# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-08-03 08:24


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giscube', '0005_auto_20180529_1051'),
    ]

    operations = [
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('url', models.GenericIPAddressField(blank=True, null=True)),
                ('token', models.CharField(blank=True, max_length=255, null=True)),
                ('this_server', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Server connection',
                'verbose_name_plural': 'Server connections',
            },
        ),
    ]
