# Generated by Django 2.1.7 on 2019-03-05 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giscube', '0008_userasset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dbconnection',
            name='engine',
            field=models.CharField(choices=[('django.contrib.gis.db.backends.postgis', 'Postgis')], max_length=255),
        ),
    ]
