# Generated by Django 2.1.7 on 2019-04-06 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giscube', '0009_auto_20190305_1011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dbconnection',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Database name'),
        ),
    ]
