# Generated by Django 2.1.7 on 2019-05-07 09:14

from django.db import migrations, models
import django.db.models.deletion
import giscube.models


class Migration(migrations.Migration):

    dependencies = [
        ('giscube', '0010_auto_20190406_1444'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userasset',
            options={'verbose_name': 'User Asset', 'verbose_name_plural': 'User Assets'},
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=50, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='giscube.Category', verbose_name='parent category'),
        ),
        migrations.AlterField(
            model_name='dbconnection',
            name='alias',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='alias'),
        ),
        migrations.AlterField(
            model_name='dbconnection',
            name='engine',
            field=models.CharField(choices=[('django.contrib.gis.db.backends.postgis', 'Postgis')], max_length=255, verbose_name='engine'),
        ),
        migrations.AlterField(
            model_name='dbconnection',
            name='host',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='host'),
        ),
        migrations.AlterField(
            model_name='dbconnection',
            name='password',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='password'),
        ),
        migrations.AlterField(
            model_name='dbconnection',
            name='port',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='port'),
        ),
        migrations.AlterField(
            model_name='dbconnection',
            name='user',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='user'),
        ),
        migrations.AlterField(
            model_name='server',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='server',
            name='this_server',
            field=models.BooleanField(default=False, verbose_name='this server'),
        ),
        migrations.AlterField(
            model_name='server',
            name='token',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='token'),
        ),
        migrations.AlterField(
            model_name='server',
            name='url',
            field=models.URLField(blank=True, null=True, verbose_name='url'),
        ),
        migrations.AlterField(
            model_name='userasset',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created'),
        ),
        migrations.AlterField(
            model_name='userasset',
            name='file',
            field=models.FileField(max_length=255, upload_to=giscube.models.user_asset_upload_to, verbose_name='file'),
        ),
    ]
