# Generated by Django 2.1.7 on 2019-05-07 09:14

from django.db import migrations, models
import django.db.models.deletion
import giscube.models


class Migration(migrations.Migration):

    dependencies = [
        ('giscube', '0010_auto_20190406_1444'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Categoria', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='dbconnection',
            options={'verbose_name': 'Connexió de base de dades', 'verbose_name_plural': 'Connexions de base de dades'},
        ),
        migrations.AlterModelOptions(
            name='server',
            options={'verbose_name': 'Connexió del servidor', 'verbose_name_plural': 'Connexions del servidor'},
        ),
        migrations.AlterModelOptions(
            name='userasset',
            options={'verbose_name': "Fitxer d'usuari", 'verbose_name_plural': "Fitxer d'usuaris"},
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=50, verbose_name='nom'),
        ),
        migrations.AlterField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='giscube.Category', verbose_name='categoria pare'),
        ),
        migrations.AlterField(
            model_name='dbconnection',
            name='alias',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='àlies'),
        ),
        migrations.AlterField(
            model_name='dbconnection',
            name='engine',
            field=models.CharField(choices=[('django.contrib.gis.db.backends.postgis', 'Postgis')], max_length=255, verbose_name='motor'),
        ),
        migrations.AlterField(
            model_name='dbconnection',
            name='host',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='host'),
        ),
        migrations.AlterField(
            model_name='dbconnection',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nom de la base de dades'),
        ),
        migrations.AlterField(
            model_name='dbconnection',
            name='password',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='contrasenya'),
        ),
        migrations.AlterField(
            model_name='dbconnection',
            name='port',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='port'),
        ),
        migrations.AlterField(
            model_name='dbconnection',
            name='user',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='usuari'),
        ),
        migrations.AlterField(
            model_name='server',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='nom'),
        ),
        migrations.AlterField(
            model_name='server',
            name='this_server',
            field=models.BooleanField(default=False, verbose_name='aquest servidor'),
        ),
        migrations.AlterField(
            model_name='server',
            name='token',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='token'),
        ),
        migrations.AlterField(
            model_name='server',
            name='url',
            field=models.URLField(blank=True, null=True, verbose_name='url'),
        ),
        migrations.AlterField(
            model_name='userasset',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='data creació'),
        ),
        migrations.AlterField(
            model_name='userasset',
            name='file',
            field=models.FileField(max_length=255, upload_to=giscube.models.user_asset_upload_to, verbose_name='fitxer'),
        ),
    ]
