# Generated by Django 2.2.11 on 2020-04-28 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giscube', '0012_giscubetransaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userasset',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='creation datetime'),
        ),
    ]
