# Generated by Django 2.2.11 on 2020-05-05 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giscube', '0014_dataset'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetadataCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='code')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='name')),
            ],
            options={
                'verbose_name': 'metadata category',
                'verbose_name_plural': 'metadata categories',
            },
        ),
    ]
