# Generated by Django 2.2.27 on 2022-05-13 07:52

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('giscube', '0025_baselayer_mapconfig_mapconfigbaselayer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mapconfigbaselayer',
            options={'ordering': ['order']},
        ),
        migrations.AlterField(
            model_name='baselayer',
            name='properties',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict, verbose_name='properties'),
        ),
    ]
