# Generated by Django 3.2.17 on 2023-06-06 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giscube', '0028_auto_20230314_1233'),
    ]

    operations = [
        migrations.AddField(
            model_name='mapconfig',
            name='active',
            field=models.BooleanField(blank=True, default=True, null=True, verbose_name='Si el mapa està actiu o no'),
        ),
        migrations.AddField(
            model_name='mapconfig',
            name='base_maps',
            field=models.TextField(blank=True, null=True, verbose_name='Mapes base disponibles pel mapa temàtic'),
        ),
        migrations.AddField(
            model_name='mapconfig',
            name='configurations',
            field=models.TextField(blank=True, null=True, verbose_name='Configuracions específiques del temàtic'),
        ),
        migrations.AddField(
            model_name='mapconfig',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Descripció del mapa'),
        ),
        migrations.AddField(
            model_name='mapconfig',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='maps/', verbose_name='Imatge miniatura'),
        ),
        migrations.AddField(
            model_name='mapconfig',
            name='layers',
            field=models.TextField(blank=True, null=True, verbose_name='Capes que se carregarran al seleccionar el mapa'),
        ),
        migrations.AddField(
            model_name='mapconfig',
            name='start',
            field=models.BooleanField(blank=True, default=True, null=True, verbose_name='Si el temàtic apareix al formulari inicial o no'),
        ),
        migrations.AddField(
            model_name='mapconfig',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Títol del mapa'),
        ),
        migrations.AddField(
            model_name='mapconfig',
            name='type',
            field=models.CharField(blank=True, choices=[('standard', 'Standard'), ('url', 'URL'), ('tool', 'Tool')], max_length=255, null=True, verbose_name='Tipus de mapa temàtic'),
        ),
        migrations.AddField(
            model_name='mapconfig',
            name='url',
            field=models.URLField(blank=True, null=True, verbose_name='URL extra'),
        ),
        migrations.AddField(
            model_name='mapconfig',
            name='visible',
            field=models.BooleanField(blank=True, default=True, null=True, verbose_name="Indica si el mapa és visible a l'iniciar la aplicació"),
        ),
    ]
