# Generated by Django 5.2 on 2025-07-29 09:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("giscube", "0029_auto_20230606_2041"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MapTool",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=255, unique=True, verbose_name="Name"),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Title")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Description"),
                ),
                (
                    "icon",
                    models.CharField(
                        help_text="Material Icon to be used on the frontend.",
                        max_length=100,
                        verbose_name="Icon",
                    ),
                ),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("action", "Frontend Action"),
                            ("url", "URL"),
                            ("webhook", "Webhook"),
                            ("to", "Frontend Route"),
                        ],
                        default="to",
                        help_text="Type of action to be triggered when using this tool.",
                        max_length=50,
                        verbose_name="Action Type",
                    ),
                ),
                (
                    "anonymous_view",
                    models.BooleanField(
                        default=False, verbose_name="Anonymous users can view"
                    ),
                ),
                (
                    "authenticated_user_view",
                    models.BooleanField(
                        default=False, verbose_name="Authenticated users can view"
                    ),
                ),
                (
                    "visible_on_geoportal",
                    models.BooleanField(
                        default=False, verbose_name="Visible on geoportal"
                    ),
                ),
                ("url", models.URLField(blank=True, null=True)),
                (
                    "to",
                    models.CharField(
                        blank=True,
                        help_text="Name of the route to redirect the user to when using this tool.",
                        max_length=200,
                        null=True,
                    ),
                ),
                (
                    "target",
                    models.CharField(
                        blank=True,
                        choices=[("_self", "Same Tab"), ("_blank", "New Tab")],
                        default="_self",
                        help_text="Tab to open the URL in.",
                        max_length=50,
                        null=True,
                        verbose_name="Target",
                    ),
                ),
                (
                    "headers",
                    models.JSONField(
                        blank=True,
                        help_text='Headers to be sent to the webhook. In JSON format. Ex: {"Authorization": "Bearer token"}',
                        null=True,
                        verbose_name="Headers",
                    ),
                ),
                (
                    "params",
                    models.JSONField(
                        blank=True,
                        help_text='Parameters to be sent in the webhook\'s body. In JSON format. Ex: {"param1": "value1", "param2": "value2"}',
                        null=True,
                        verbose_name="Parameters",
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0, verbose_name="Ordre")),
            ],
            options={
                "verbose_name": "Map Tool",
                "verbose_name_plural": "Map Tools",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="MapToolGroupPermission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "can_view",
                    models.BooleanField(default=True, verbose_name="Can view"),
                ),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="auth.group",
                        verbose_name="Group",
                    ),
                ),
                (
                    "maptool",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="group_permissions",
                        to="giscube.maptool",
                    ),
                ),
            ],
            options={
                "verbose_name": "Group",
                "verbose_name_plural": "Groups",
            },
        ),
        migrations.CreateModel(
            name="MapToolUserPermission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "can_view",
                    models.BooleanField(default=True, verbose_name="Can view"),
                ),
                (
                    "maptool",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_permissions",
                        to="giscube.maptool",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "User",
                "verbose_name_plural": "Users",
            },
        ),
    ]
