# Generated by Django 3.2.17 on 2026-04-29 12:17

from django.db import migrations
from django.conf import settings


def create_geoportal_oauth2_application(apps, schema_editor):
    Application = apps.get_model('oauth2_provider', 'Application')
    application_name = settings.OAUTH2_GEOPORTAL_APPLICATION_NAME
    Application.objects.get_or_create(
        name=application_name,
        defaults={
            "client_type": "public",
            "authorization_grant_type": "password",
        },
    )


class Migration(migrations.Migration):

    dependencies = [
        ('giscube', '0031_accesslog_userslog'),
    ]

    operations = [
        migrations.RunPython(create_geoportal_oauth2_application),
    ]
