# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-08-03 08:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giscube', '0006_server'),
        ('qgisserver', '0010_auto_20180531_1458'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='servers',
            field=models.ManyToManyField(blank=True, to='giscube.Server'),
        ),
        migrations.AlterField(
            model_name='service',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
