# Generated by Django 2.1.7 on 2019-03-05 10:11

from django.db import migrations, models
import qgisserver.models


class Migration(migrations.Migration):

    dependencies = [
        ('qgisserver', '0011_auto_20180803_0824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='visibility',
            field=models.CharField(choices=[('private', 'Private'), ('public', 'Public')], default='private', max_length=10),
        ),
        migrations.AlterField(
            model_name='service',
            name='wms_buffer_enabled',
            field=models.BooleanField(default=False, verbose_name='buffer enabled'),
        ),
        migrations.AlterField(
            model_name='service',
            name='wms_buffer_size',
            field=models.CharField(blank=True, help_text='Buffer around tiles, e.g. 64,64', max_length=12, null=True, validators=[qgisserver.models.validate_integer_pair], verbose_name='buffer size'),
        ),
        migrations.AlterField(
            model_name='service',
            name='wms_tile_sizes',
            field=models.TextField(blank=True, help_text='Integer pairs in different lines e.g.<br/>256,256<br/>512,512', null=True, validators=[qgisserver.models.validate_integer_pair_list], verbose_name='tile sizes'),
        ),
    ]
