# Generated by Django 2.1.7 on 2019-05-07 09:14

from django.db import migrations, models
import giscube.validators
import qgisserver.models
import qgisserver.utils


class Migration(migrations.Migration):

    dependencies = [
        ('qgisserver', '0014_service_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'verbose_name': 'Projecte', 'verbose_name_plural': 'Projectes'},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'verbose_name': 'Servei', 'verbose_name_plural': 'Serveis'},
        ),
        migrations.AlterField(
            model_name='project',
            name='data',
            field=models.TextField(blank=True, null=True, verbose_name='dades'),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=50, verbose_name='nom'),
        ),
        migrations.AlterField(
            model_name='service',
            name='active',
            field=models.BooleanField(default=True, help_text='Enable/disable usage', verbose_name='actiu'),
        ),
        migrations.AlterField(
            model_name='service',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='descripció'),
        ),
        migrations.AlterField(
            model_name='service',
            name='keywords',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='paraules clau'),
        ),
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='nom'),
        ),
        migrations.AlterField(
            model_name='service',
            name='options',
            field=models.TextField(blank=True, help_text='json format. Ex: {"maxZoom": 20}', null=True, validators=[giscube.validators.validate_options_json_format], verbose_name='opcions'),
        ),
        migrations.AlterField(
            model_name='service',
            name='project_file',
            field=models.FileField(upload_to=qgisserver.utils.unique_service_directory, verbose_name='fitxe del projecte'),
        ),
        migrations.AlterField(
            model_name='service',
            name='service_path',
            field=models.CharField(max_length=255, verbose_name='service path'),
        ),
        migrations.AlterField(
            model_name='service',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='títol'),
        ),
        migrations.AlterField(
            model_name='service',
            name='visibility',
            field=models.CharField(choices=[('private', 'Privat'), ('public', 'Públic')], default='private', help_text="visibility='Private' restricts usage to authenticated users", max_length=10, verbose_name='visibilitat'),
        ),
        migrations.AlterField(
            model_name='service',
            name='visible_on_geoportal',
            field=models.BooleanField(default=False, verbose_name='visible al geoportal'),
        ),
        migrations.AlterField(
            model_name='service',
            name='wms_buffer_enabled',
            field=models.BooleanField(default=False, verbose_name='buffer actiu'),
        ),
        migrations.AlterField(
            model_name='service',
            name='wms_buffer_size',
            field=models.CharField(blank=True, help_text='Buffer around tiles, e.g. 64,64', max_length=12, null=True, validators=[qgisserver.models.validate_integer_pair], verbose_name='mida del buffer'),
        ),
        migrations.AlterField(
            model_name='service',
            name='wms_tile_sizes',
            field=models.TextField(blank=True, help_text='Integer pairs in different lines e.g.<br/>256,256<br/>512,512', null=True, validators=[qgisserver.models.validate_integer_pair_list], verbose_name='mida dels tiles'),
        ),
    ]
