# Generated by Django 3.0.10 on 2020-11-11 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qgisserver', '0020_serviceresource_downloadable'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceresource',
            name='content_type',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='content type'),
        ),
    ]
