# Generated by Django 2.2.17 on 2020-11-20 12:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qgisserver', '0021_serviceresource_content_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='tilecache_bbox',
            field=models.CharField(blank=True, help_text='The format is: xmin,ymin,xmin,xmax. BBOX coordinates must be in EPSG:4326', max_length=255, null=True, verbose_name='BBOX'),
        ),
        migrations.AddField(
            model_name='service',
            name='tilecache_enabled',
            field=models.BooleanField(default=False, verbose_name='enabled'),
        ),
        migrations.AddField(
            model_name='service',
            name='tilecache_maxzoom_level',
            field=models.SmallIntegerField(default=22, validators=[django.core.validators.MaxValueValidator(30), django.core.validators.MinValueValidator(0)], verbose_name='maximum zoom level'),
        ),
        migrations.AddField(
            model_name='service',
            name='tilecache_minzoom_level',
            field=models.SmallIntegerField(default=4, validators=[django.core.validators.MaxValueValidator(24), django.core.validators.MinValueValidator(0)], verbose_name='minimum zoom level'),
        ),
        migrations.AddField(
            model_name='service',
            name='tilecache_transparent',
            field=models.BooleanField(default=True, verbose_name='force transparent'),
        ),
    ]
