# Generated by Django 2.2.17 on 2020-11-27 13:50

from django.db import migrations, models
import qgisserver.models


class Migration(migrations.Migration):

    dependencies = [
        ('qgisserver', '0024_auto_20201123_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='project_file',
            field=models.FileField(upload_to=qgisserver.models.project_unique_service_directory, verbose_name='project file'),
        ),
    ]
