# Generated by Django 2.2.17 on 2021-03-22 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qgisserver', '0025_auto_20201127_1450'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='wms_getfeatureinfo_enabled',
            field=models.BooleanField(default=True, verbose_name='WMS GetFeatureInfo enabled'),
        )
    ]

