# Generated by Django 2.2.17 on 2021-04-20 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qgisserver', '0027_fix_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicegrouppermission',
            name='can_write',
            field=models.BooleanField(default=True, verbose_name='Can write'),
        ),
        migrations.AddField(
            model_name='serviceuserpermission',
            name='can_write',
            field=models.BooleanField(default=True, verbose_name='Can write'),
        ),
    ]
