# Generated by Django 3.2.17 on 2023-04-03 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qgisserver', '0030_auto_20230314_1233'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='popup',
            field=models.TextField(blank=True, help_text='Field between curly braces. e.g. {street}', null=True, verbose_name='popup'),
        ),
    ]
