# Generated by Django 3.2.17 on 2024-10-10 10:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qgisserver', '0033_service_tilecache_expiration_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='tilecache_maxZoom_level_chached',
            field=models.SmallIntegerField(default=22, validators=[django.core.validators.MinValueValidator(0)], verbose_name='max zoom level cached'),
        ),
        migrations.AddField(
            model_name='service',
            name='tilecache_minZoom_level_chached',
            field=models.SmallIntegerField(default=4, validators=[django.core.validators.MinValueValidator(0)], verbose_name='min zoom level cached'),
        ),
    ]
