# Generated by Django 3.2.17 on 2025-01-09 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qgisserver', '0034_auto_20241010_1202'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='service_type',
            field=models.CharField(choices=[('wms', 'WMS'), ('wmts', 'WMTS')], default='wms', max_length=255, verbose_name='service type'),
        ),
    ]
