# Generated by Django 3.2.17 on 2025-04-16 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qgisserver', '0034_auto_20241010_1202'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='choose_individual_layers',
        ),
        migrations.RemoveField(
            model_name='service',
            name='read_layers_automatically',
        ),
        migrations.CreateModel(
            name='ServiceFilter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50, null=True, verbose_name='title')),
                ('layers', models.TextField(blank=True, null=True, verbose_name='layers')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filters', to='qgisserver.service')),
            ],
        ),
    ]
