# Generated by Django 3.2.17 on 2025-07-03 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qgisserver', '0035_auto_20250416_1547'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='catalog_color',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='catalog color'),
        ),
        migrations.AddField(
            model_name='servicefilter',
            name='catalog_color',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='catalog color'),
        ),
    ]
