# Generated by Django 3.2.17 on 2025-09-18 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qgisserver', '0036_auto_20250703_1313'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='wfs_enabled',
            field=models.BooleanField(default=False, verbose_name='enabled'),
        ),
        migrations.AddField(
            model_name='service',
            name='wfs_transaction_enabled',
            field=models.BooleanField(default=True, verbose_name="'Transaction' requests enabled"),
        ),
    ]
