# Generated by Django 3.2.17 on 2026-03-30 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qgisserver', '0038_service_service_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceresource',
            name='style',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='style'),
        ),
        migrations.AddField(
            model_name='serviceresource',
            name='tile_matrix_set',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='tile matrix set'),
        ),
        migrations.AlterField(
            model_name='service',
            name='wfs_transaction_enabled',
            field=models.BooleanField(default=True, verbose_name='Transaction requests enabled'),
        ),
        migrations.AlterField(
            model_name='serviceresource',
            name='type',
            field=models.CharField(choices=[('TMS', 'TMS'), ('WMS', 'WMS'), ('WMTS', 'WMTS'), ('document', 'Document'), ('url', 'URL')], max_length=12, verbose_name='type'),
        ),
    ]
