# Generated by Django 3.2.17 on 2026-05-08 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giscube', '0033_dataset_additional_categories'),
        ('qgisserver', '0038_service_service_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='additional_categories',
            field=models.ManyToManyField(blank=True, null=True, related_name='qgisserver_services_categories', to='giscube.Category', verbose_name='additional categories'),
        ),
        migrations.AlterField(
            model_name='service',
            name='wfs_transaction_enabled',
            field=models.BooleanField(default=True, verbose_name='Transaction requests enabled'),
        ),
    ]
